### ISSUE TITLE
[bug] it's possible to bypass initial setup screen and be stuck afterwards

### ISSUE THREAD

**Issue by jozan** [expo/orbit#18]
i downloaded the Expo Orbit and launched it for the first time. setup i don't see any installed simulators or emulators in menubar dropdown. do i need both android and iOS environments working to be able to continue? or should iOS environment be enough?

my Xcode setup is working correctly and i have simulators installed and working.

## repro steps:
1. open Expo Orbit and see pre-flight checklist screen (**image 1**)
2. spinners spin for a minute
3. press Get Started button
4. see that there are simulator and emulator list is not populated (**image 2**)

| image 1 | image 2 |
| ------- | ------- |
| <img width="512" alt="image" src="https://github.com/expo/orbit/assets/388265/04266204-6826-4d64-b229-5ee2c3165493"> | <img width="452" alt="image" src="https://github.com/expo/orbit/assets/388265/fa62cca7-e30c-4c0a-bbd4-739d210d7b8e"> |

## environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5
      Shell: 3.6.1 - /usr/local/bin/fish
    Binaries:
      Node: 20.5.0 - ~/n/bin/node
      Yarn: 3.5.0 - ~/n/bin/yarn
      npm: 9.8.0 - ~/n/bin/npm
      Watchman: 2023.07.24.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.0
      react: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
    Expo Workflow: managed
```

**Comment by lklima** [comment]
same here 😕

**Comment by gabrieldonadel** [comment]
Hi @jozan, the cause of this is related to a misconfigured Android SDK path, but later today I'll be releasing a new version of Orbit that contains a fix for this and a couple of other things.

**Comment by gabrieldonadel** [comment]
A new version of Expo Orbit has just been released! [v0.1.1](https://github.com/expo/orbit/releases/tag/expo-orbit-v0.1.1) includes fixes for this and other issues, you can check the full details on the [releases page](https://github.com/expo/orbit/releases). Please test it out and let us know if you find any other problems.

**Comment by steveliles** [comment]
I just downloaded orbit 1.0.3 (20) and seem to have exactly this issue. 

I have android studio and xcode installed and working, and my expo app runs fine in simulators and on real devices.

When I fired it up for the first time the Android Studio and Xcode spinners were spinning away ... i waited over a minute but figured, since the "get started" button was active, it wouldn't hurt to proceed and that whatever those spinners were doing would continue in the background. 

Now orbit is running and i'm logged in to my expo.dev account, but it doesn't seem to see my environment correctly, e.g. if i try to launch a build from the "Open with Orbit" button in my Expo.dev account I see this:

![Screenshot 2024-02-05 at 09 31 48](https://github.com/expo/orbit/assets/441745/95cfea21-e316-4eee-9a1f-496071adf750)

There doesn't seem to be any way to get back to that initial screen or fix the configuration (at least for ios).

**Comment by steveliles** [comment]
I originally installed from downloaded zip. removed that and re-installed via brew. first start after reinstall completely skipped the intro screen because i still had ~/.expo/orbit directory. removed that and restarted and now i have infinite spinners in both the Android Studio and Xcode boxes (same situation i had at initial start of original downloaded from zip). AFAIK there is nothing unusual about my xcode or android studio installations, so i'm not sure why this would get stuck.

**Comment by gabrieldonadel** [comment]
Hi @steveliles, the command is probably failing to run, are you using an Intel mac by any chance?

Can you run this command on your machine and paste the output?

```sh
# If have a M1/M2 computer
/Applications/Expo\ Orbit.app/Contents/Resources/orbit-cli-arm64 list-devices

# If you have an Intel
/Applications/Expo\ Orbit.app/Contents/Resources/orbit-cli-x64 list-devices

```

**Comment by steveliles** [comment]
yeah intel mac (stuck in 2018 😭), which looks to be the issue from this:

```
/Applications/Expo\ Orbit.app/Contents/Resources/orbit-cli-x64 list-devices
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: dlopen(/var/folders/vc/yp6d_9ws6t96d2hd_w651s4c0000gn/T/pkg/c5365aef9f7b6224df562ebc0189dc78ebe995c2ccd4c1641112e9482cffc687/nodejs-mmkv/build/Release/nodejs-mmkv.node, 0x0001): tried: '/var/folders/vc/yp6d_9ws6t96d2hd_w651s4c0000gn/T/pkg/c5365aef9f7b6224df562ebc0189dc78ebe995c2ccd4c1641112e9482cffc687/nodejs-mmkv/build/Release/nodejs-mmkv.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/vc/yp6d_9ws6t96d2hd_w651s4c0000gn/T/pkg/c5365aef9f7b6224df562ebc0189dc78ebe995c2ccd4c1641112e9482cffc687/nodejs-mmkv/build/Release/nodejs-mmkv.node' (no such file), '/var/folders/vc/yp6d_9ws6t96d2hd_w651s4c0000gn/T/pkg/c5365aef9f7b6224df562ebc0189dc78ebe995c2ccd4c1641112e9482cffc687/nodejs-mmkv/build/Release/nodejs-mmkv.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/private/var/folders/vc/yp6d_9ws6t96d2hd_w651s4c0000gn/T/pkg/c5365aef9f7b6224df562ebc0189dc78ebe995c2ccd4c1641112e9482cffc687/nodejs-mmkv/build/Release/nodejs-mmkv.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/vc/yp6d_9ws6t96d2hd_w651s4c0000gn/T/pkg/c5365aef9f7b6224df562ebc0189dc78ebe995c2ccd4c1641112e9482cffc687/nodejs-mmkv/build/Release/nodejs-mmkv.node' (no such file), '/private/var/folders/vc/yp6d_9ws6t96d2hd_w651s4c0000gn/T/pkg/c5365aef9f7b6224df562ebc0189dc78ebe995c2ccd4c1641112e9482cffc687/nodejs-mmkv/build/Release/nodejs-mmkv.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))
    at process.dlopen (pkg/prelude/bootstrap.js:2251:28)
    at Module._extensions..node (node:internal/modules/cjs/loader:1196:18)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/snapshot/ExpoMenuBar/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/snapshot/ExpoMenuBar/node_modules/nodejs-mmkv/index.js:1:105)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.5.0
```

**Comment by gabrieldonadel** [comment]
I see, thanks for the logs @steveliles, I was able to reproduce this on my machine, seems that 1.0.3 is currently broken on x64. For now, I recommend downgrading to 1.0.2 https://github.com/expo/orbit/releases/tag/expo-orbit-v1.0.2. I'll be working on a fix for this and will release a new version ASAP

**Comment by steveliles** [comment]
great - thanks for the quick response

**Comment by gabrieldonadel** [comment]
Hi @steveliles, a new version of Expo Orbit has just been released! [v1.0.4](https://github.com/expo/orbit/releases/tag/expo-orbit-v1.0.4) includes fixes for this and other issues, you can check the full details on the [releases page](https://github.com/expo/orbit/releases). Please test it out and let us know if you find any other problems.
